title: "Kengo Ohta"
description: "Personal web site"
url: "https://ota.github.io"
baseurl: ""
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge

defaults:
    - scope:
          path: ""
      values:
          layout: default
